# Generated by Django 5.1.3 on 2024-11-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='publish_date',
        ),
    ]
