# Generated by Django 5.1.4 on 2025-01-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_internallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internallink',
            name='destination',
        ),
        migrations.AddField(
            model_name='internallink',
            name='destination_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AddField(
            model_name='internallink',
            name='destination_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
        migrations.AddField(
            model_name='internallink',
            name='destination_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tag'),
        ),
        migrations.AddField(
            model_name='internallink',
            name='destination_type',
            field=models.CharField(choices=[('C', 'Category'), ('P', 'Post'), ('T', 'Tag')], default='P', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='internallink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_post__isnull', True), ('destination_tag__isnull', True), ('destination_type', 'C')), models.Q(('destination_category__isnull', True), ('destination_tag__isnull', True), ('destination_type', 'P')), models.Q(('destination_category__isnull', True), ('destination_post__isnull', True), ('destination_type', 'T')), _connector='OR'), name='blog_internallink_only_one_destination'),
        ),
    ]
