# Generated by Django 5.1.4 on 2025-01-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_image_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_hash',
            field=models.CharField(default=7, max_length=40),
            preserve_default=False,
        ),
    ]
