# Generated by Django 5.1.4 on 2025-01-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_image_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.CharField(default='filler', max_length=1000),
            preserve_default=False,
        ),
    ]
