# Generated by Django 5.1.4 on 2025-01-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_image_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_hash',
            field=models.CharField(editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.CharField(editable=False, max_length=1000),
        ),
    ]
