# Generated by Django 5.1.4 on 2025-01-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_image_image_hash_alter_image_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='upload_date',
        ),
    ]
